<?php
/** Administrator-only /dashboard management endpoints. */
if(!defined('ABSPATH'))exit;
function ggm_dashboard_user_is_administrator(){if(!is_user_logged_in()||!current_user_can( 'manage_options' ))return false;$user=wp_get_current_user();return $user&&in_array('administrator',(array)$user->roles,true);}
class GGM_Dashboard_Management{
	public function init(GGM_Loader $loader){foreach(array('bootstrap','workshops','workshop_load','workshop_save','courses','course_load','course_save','members','payments','payment_refund','diseases','disease_save')as $a)$loader->add_action('wp_ajax_ggm_dashboard_management_'.$a,$this,'ajax_'.$a);}
	private function authorize(){check_ajax_referer('ggm_dashboard_management','nonce');if(!ggm_dashboard_user_is_administrator())wp_send_json_error(array('message'=>__('Administrator authorization is required.','ggm-member-dashboard')),403);}
	private function payload(){$raw=wp_unslash($_POST['payload']??'');$data=is_string($raw)?json_decode($raw,true):$raw;return is_array($data)?$data:array();}
	public function ajax_bootstrap(){$this->authorize();$map=static function($p){return array('id'=>$p->ID,'title'=>$p->post_title);};$posts=static function($types){return get_posts(array('post_type'=>$types,'post_status'=>array('publish','draft'),'posts_per_page'=>-1,'orderby'=>'title','order'=>'ASC'));};wp_send_json_success(array('workshops'=>array_map($map,$posts(array('workshop','ggm_workshop'))),'mentors'=>array_map($map,$posts('ggm_mentor')),'courses'=>array_map($map,$posts('course')),'slot_types'=>class_exists('GGM_Workshop_Slot')?GGM_Workshop_Slot::types():array(),'currencies'=>class_exists('GGM_Currency')?GGM_Currency::enabled_codes():array('INR'),'base_currency'=>class_exists('GGM_Currency')?GGM_Currency::base_currency():'INR','workshop_configuration'=>class_exists('GGM_Workshop_Admin_Config')?GGM_Workshop_Admin_Config::get():array()));}
	public function ajax_workshops(){$this->authorize();$this->send_post_list(array('workshop','ggm_workshop'));}public function ajax_courses(){$this->authorize();$this->send_post_list(array('course'));}
	private function send_post_list($types){$page=max(1,absint($_POST['page']??1));$search=sanitize_text_field(wp_unslash($_POST['search']??''));$status=sanitize_key(wp_unslash($_POST['status']??''));$q=new WP_Query(array('post_type'=>$types,'post_status'=>in_array($status,array('publish','draft'),true)?$status:array('publish','draft'),'s'=>$search,'posts_per_page'=>20,'paged'=>$page));$items=array_map(static function($p){return array('id'=>$p->ID,'title'=>$p->post_title,'status'=>$p->post_status,'date'=>get_the_date('',$p),'type'=>$p->post_type,'edit'=>current_user_can('edit_post',$p->ID));},$q->posts);wp_send_json_success(array('items'=>$items,'page'=>$page,'pages'=>(int)$q->max_num_pages,'total'=>(int)$q->found_posts,'per_page'=>20));}
	public function ajax_workshop_load(){$this->authorize();$id=absint($_POST['id']??0);if(!current_user_can('edit_post',$id))wp_send_json_error(array('message'=>__('You cannot edit this Workshop.','ggm-member-dashboard')),403);$item=GGM_Workshop_Data_Service::load($id);is_wp_error($item)?wp_send_json_error(array('message'=>$item->get_error_message()),404):wp_send_json_success($item);}
	public function ajax_course_load(){$this->authorize();$id=absint($_POST['id']??0);if(!current_user_can('edit_post',$id))wp_send_json_error(array('message'=>__('You cannot edit this Course.','ggm-member-dashboard')),403);$item=GGM_Course_Data_Service::load($id);is_wp_error($item)?wp_send_json_error(array('message'=>$item->get_error_message()),404):wp_send_json_success($item);}
	public function ajax_workshop_save(){$this->authorize();$p=$this->payload();unset($p['excerpt']);$this->save_post($p,'workshop','GGM_Workshop_Data_Service',array('workshop','ggm_workshop'));}
	public function ajax_course_save(){$this->authorize();$this->save_post($this->payload(),'course','GGM_Course_Data_Service',array('course'));}
	private function save_post($p,$type,$service,$types){$id=absint($p['id']??0);$status=in_array($p['status']??'draft',array('publish','draft'),true)?$p['status']:'draft';if($id){if(!current_user_can('edit_post',$id)||!in_array(get_post_type($id),$types,true))wp_send_json_error(array('message'=>__('You cannot edit this item.','ggm-member-dashboard')),403);$result=wp_update_post(wp_slash(array('ID'=>$id,'post_title'=>sanitize_text_field($p['title']??''),'post_content'=>wp_kses_post($p['content']??''),'post_status'=>$status)),true);}else $result=wp_insert_post(wp_slash(array('post_type'=>$type,'post_title'=>sanitize_text_field($p['title']??''),'post_content'=>wp_kses_post($p['content']??''),'post_status'=>$status)),true);if(is_wp_error($result))wp_send_json_error(array('message'=>$result->get_error_message()),400);$saved=call_user_func(array($service,'save'),$result,$p);if(is_wp_error($saved))wp_send_json_error(array('message'=>$saved->get_error_message()),400);wp_send_json_success(array('message'=>__('Saved successfully.','ggm-member-dashboard'),'item'=>$saved));}
	public function ajax_members(){$this->authorize();$result=GGM_Member_Data_Service::query(array('search'=>wp_unslash($_POST['search']??''),'workshop_id'=>$_POST['workshop_id']??0,'page'=>$_POST['page']??1));if(is_wp_error($result))wp_send_json_error(array('message'=>$result->get_error_message()),$result->get_error_code()==='invalid_workshop'?400:500);$result['items']=$result['rows'];$result['members']=$result['rows'];unset($result['rows']);$result['diagnostic']=array_merge((array)($result['diagnostic']??array()),array('source'=>$result['source'],'page'=>$result['page'],'returned'=>count($result['items']),'total'=>$result['total']));$result['empty_message']=!empty($result['workshop_id'])?__('No Customers are assigned to this Workshop.','ggm-member-dashboard'):__('No Customer users match the current filters.','ggm-member-dashboard');wp_send_json_success($result);}
	public function ajax_payments(){$this->authorize();wp_send_json_success(GGM_Payment_Admin_Service::query(array('search'=>wp_unslash($_POST['search']??''),'status'=>wp_unslash($_POST['status']??''),'page'=>$_POST['page']??1)));}
	public function ajax_payment_refund(){$this->authorize();$id=absint($_POST['payment_id']??0);$refund_nonce=sanitize_text_field(wp_unslash($_POST['refund_nonce']??''));if(!$id||!wp_verify_nonce($refund_nonce,'ggm_refund_'.$id))wp_send_json_error(array('message'=>__('Invalid refund request.','ggm-member-dashboard')),403);$result=GGM_Payment_Admin_Service::refund($id);is_wp_error($result)?wp_send_json_error(array('message'=>$result->get_error_message()),400):wp_send_json_success(array('message'=>__('Payment marked as refunded.','ggm-member-dashboard')));}
	public function ajax_diseases(){
		$this->authorize();
		if(!class_exists('GGM_Diseases'))wp_send_json_error(array('message'=>__('Disease management is unavailable.','ggm-member-dashboard')),500);
		$result=GGM_Diseases::query_active($_POST['page']??1,wp_unslash($_POST['search']??''),10);
		$items=array_map(static function($disease){return array(
			'id'=>(int)$disease->id,
			'title'=>(string)$disease->title,
			'description'=>(string)$disease->description,
			'excerpt'=>wp_trim_words(wp_strip_all_tags($disease->description),18),
			'updated'=>mysql2date(get_option('date_format'),$disease->updated_at),
		);},$result['items']);
		wp_send_json_success(array('items'=>$items,'page'=>$result['page'],'pages'=>$result['pages'],'total'=>$result['total'],'per_page'=>$result['per_page'],'empty_message'=>__('No diseases found.','ggm-member-dashboard')));
	}
	public function ajax_disease_save(){
		$this->authorize();
		if(!class_exists('GGM_Diseases'))wp_send_json_error(array('message'=>__('Disease management is unavailable.','ggm-member-dashboard')),500);
		$result=GGM_Diseases::save($_POST['id']??0,$_POST['title']??'',$_POST['description']??'');
		if(is_wp_error($result))wp_send_json_error(array('message'=>$result->get_error_message()),$result->get_error_code()==='ggm_disease_not_found'?404:400);
		$disease=GGM_Diseases::get_active($result['id']);
		wp_send_json_success(array('message'=>'created'===$result['notice']?__('Disease created successfully.','ggm-member-dashboard'):__('Disease saved successfully.','ggm-member-dashboard'),'item'=>array('id'=>(int)$disease->id,'title'=>(string)$disease->title,'description'=>(string)$disease->description,'excerpt'=>wp_trim_words(wp_strip_all_tags($disease->description),18),'updated'=>mysql2date(get_option('date_format'),$disease->updated_at))));
	}
}
