<?php if ( ! defined( 'ABSPATH' ) ) exit; ?>
<section class="ggm-workshop-section" data-workshop-section="basic"><h3><?php esc_html_e('Basic Information','ggm-member-dashboard'); ?></h3><label><?php esc_html_e('Workshop Title','ggm-member-dashboard'); ?><input required name="title"></label><label for="ggm-dashboard-workshop-content"><?php esc_html_e('Workshop Content','ggm-member-dashboard'); ?></label><?php wp_editor( '', 'ggm-dashboard-workshop-content', array( 'textarea_name' => 'content', 'textarea_rows' => 10, 'media_buttons' => true, 'teeny' => false, 'quicktags' => true ) ); ?><div data-ggm-media="featured_image_id"></div></section>
<section class="ggm-workshop-section" data-workshop-section="workshop_details"><h3><?php esc_html_e('Workshop Details','ggm-member-dashboard'); ?></h3><div class="ggm-workshop-grid" data-ggm-details></div></section>
<section class="ggm-workshop-section" data-workshop-section="pricing"><h3><?php esc_html_e('Pricing','ggm-member-dashboard'); ?></h3><div data-ggm-pricing></div></section>
<section class="ggm-workshop-section" data-workshop-section="booking_card"><h3><?php esc_html_e('Booking Card','ggm-member-dashboard'); ?></h3><div data-ggm-booking></div></section>
<section class="ggm-workshop-section" data-workshop-section="form_text"><h3><?php esc_html_e('Form Text','ggm-member-dashboard'); ?></h3><label><?php esc_html_e('Heading','ggm-member-dashboard'); ?><input name="ggm_workshop_form_text_heading"></label><label for="ggm-dashboard-workshop-form-text"><?php esc_html_e('Content','ggm-member-dashboard'); ?></label><?php wp_editor( '', 'ggm-dashboard-workshop-form-text', array( 'textarea_name' => 'ggm_workshop_form_text_content', 'textarea_rows' => 10, 'media_buttons' => true, 'teeny' => false, 'quicktags' => true ) ); ?></section>
<section class="ggm-workshop-section" data-workshop-section="time_slots"><h3><?php esc_html_e('Workshop Time Slots','ggm-member-dashboard'); ?></h3><div data-ggm-slots></div><button type="button" class="ggm-btn" data-ggm-add-slot><?php esc_html_e('+ Add Time Slot','ggm-member-dashboard'); ?></button></section>
<section class="ggm-workshop-section" data-workshop-section="additional_layout"><h3><?php esc_html_e('Additional Block Layout','ggm-member-dashboard'); ?></h3><div data-ggm-layout></div></section>
<section class="ggm-workshop-section" data-workshop-section="discover"><h3><?php esc_html_e('You Will Discover','ggm-member-dashboard'); ?></h3><div data-ggm-repeater="ggm_you_will_discover"></div></section>
<section class="ggm-workshop-section" data-workshop-section="why_different"><h3><?php esc_html_e('Why Different','ggm-member-dashboard'); ?></h3><div data-ggm-repeater="ggm_why_different_points"></div></section>
<section class="ggm-workshop-section" data-workshop-section="why_workshop_different"><h3><?php esc_html_e('Why This Workshop Is Different','ggm-member-dashboard'); ?></h3><div data-ggm-why-workshop></div></section>
<section class="ggm-workshop-section" data-workshop-section="journey"><h3><?php esc_html_e('Workshop Journey','ggm-member-dashboard'); ?></h3><div data-ggm-repeater="ggm_workshop_journey_days"></div><div data-ggm-journey-footer></div></section>
<section class="ggm-workshop-section" data-workshop-section="perfect_for"><h3><?php esc_html_e('Perfect For You','ggm-member-dashboard'); ?></h3><div data-ggm-repeater="ggm_perfect_for_you"></div></section>
<section class="ggm-workshop-section" data-workshop-section="faq"><h3><?php esc_html_e('FAQ','ggm-member-dashboard'); ?></h3><div data-ggm-repeater="ggm_faq"></div></section>
