<?php
/** Shared, non-rendering Course and lesson data service. */
if ( ! defined( 'ABSPATH' ) ) { exit; }
class GGM_Course_Data_Service {
	public static function load( $id ) {
		$post = get_post( absint( $id ) );
		if ( ! $post || 'course' !== $post->post_type ) return new WP_Error( 'invalid_course', __( 'Course not found.', 'ggm-member-dashboard' ) );
		$lessons = get_posts( array( 'post_type' => array( 'lesson', 'ggm_lesson' ), 'post_status' => array( 'publish', 'draft' ), 'posts_per_page' => -1, 'meta_key' => 'lesson_order', 'orderby' => 'meta_value_num', 'order' => 'ASC', 'meta_query' => array( array( 'key' => 'course', 'value' => $post->ID ) ) ) );
		$image_id = get_post_thumbnail_id( $post->ID );
		return array( 'id' => $post->ID, 'title' => $post->post_title, 'content' => $post->post_content, 'status' => $post->post_status, 'featured_image_id' => $image_id, 'featured_image' => $image_id ? array( 'id' => $image_id, 'url' => wp_get_attachment_image_url( $image_id, 'medium' ) ) : null, 'meta' => array( 'course_price' => get_post_meta( $post->ID, 'course_price', true ), 'course_short_description' => get_post_meta( $post->ID, 'course_short_description', true ), 'course_language' => get_post_meta( $post->ID, 'course_language', true ), 'course_duration' => get_post_meta( $post->ID, 'course_duration', true ), 'course_instructor' => get_post_meta( $post->ID, 'course_instructor', true ), 'ggm_mentor_ids' => get_post_meta( $post->ID, 'ggm_mentor_ids', true ) ), 'lessons' => array_map( array( __CLASS__, 'lesson_data' ), $lessons ) );
	}
	public static function lesson_data( $lesson ) {
		$focus = json_decode( get_post_meta( $lesson->ID, 'lesson_focus_areas', true ), true );
		return array( 'id' => $lesson->ID, 'title' => $lesson->post_title, 'content' => $lesson->post_content, 'status' => $lesson->post_status, 'order' => (int) get_post_meta( $lesson->ID, 'lesson_order', true ), 'duration' => get_post_meta( $lesson->ID, 'lesson_duration', true ), 'video_embed' => get_post_meta( $lesson->ID, 'video_embed', true ), 'is_preview' => '1' === get_post_meta( $lesson->ID, 'is_preview', true ), 'what_to_expect' => get_post_meta( $lesson->ID, 'what_to_expect', true ), 'best_practices' => get_post_meta( $lesson->ID, 'best_practices', true ), 'lesson_resources_pdf' => get_post_meta( $lesson->ID, 'lesson_resources_pdf', true ), 'lesson_summary' => get_post_meta( $lesson->ID, 'lesson_summary', true ), 'focus_areas' => is_array( $focus ) ? $focus : array() );
	}
	public static function save( $id, array $payload ) {
		$post = get_post( absint( $id ) );
		if ( ! $post || 'course' !== $post->post_type ) return new WP_Error( 'invalid_course', __( 'Course not found.', 'ggm-member-dashboard' ) );
		foreach ( array( 'course_price', 'course_short_description', 'course_language', 'course_duration', 'course_instructor' ) as $key ) if ( array_key_exists( $key, $payload ) ) { $value = 'course_short_description' === $key ? sanitize_textarea_field( $payload[ $key ] ) : sanitize_text_field( $payload[ $key ] ); if ( 'course_language' === $key ) $value = in_array( strtolower( $value ), array( 'english', 'hindi' ), true ) ? strtolower( $value ) : 'english'; update_post_meta( $id, $key, $value ); }
		if ( isset( $payload['ggm_mentor_ids'] ) ) { $mentors = array_values( array_unique( array_filter( array_map( 'absint', (array) $payload['ggm_mentor_ids'] ) ) ) ); update_post_meta( $id, 'ggm_mentor_ids', $mentors ); update_post_meta( $id, 'ggm_mentor_id', $mentors[0] ?? 0 ); }
		if ( array_key_exists( 'featured_image_id', $payload ) ) { $image = absint( $payload['featured_image_id'] ); if ( $image && ( ! wp_attachment_is_image( $image ) || ! current_user_can( 'edit_post', $image ) ) ) return new WP_Error( 'invalid_featured_image', __( 'The selected featured image is not available to edit.', 'ggm-member-dashboard' ) ); if ( $image ) set_post_thumbnail( $id, $image ); else delete_post_thumbnail( $id ); }
		if ( array_key_exists( 'lessons', $payload ) ) { $saved = self::save_lessons( $id, (array) $payload['lessons'] ); if ( is_wp_error( $saved ) ) return $saved; }
		foreach ( array_unique( array_map( 'absint', (array) ( $payload['detach_lesson_ids'] ?? array() ) ) ) as $lesson_id ) { $lesson = get_post( $lesson_id ); if ( ! $lesson || ! in_array( $lesson->post_type, array( 'lesson', 'ggm_lesson' ), true ) || (int) get_post_meta( $lesson_id, 'course', true ) !== (int) $id || ! current_user_can( 'edit_post', $lesson_id ) ) continue; delete_post_meta( $lesson_id, 'course' ); }
		clean_post_cache( $id ); return self::load( $id );
	}
	private static function save_lessons( $course_id, array $lessons ) {
		foreach ( $lessons as $order => $lesson ) { $lesson_id = absint( $lesson['id'] ?? 0 ); $data = array( 'post_title' => sanitize_text_field( $lesson['title'] ?? '' ), 'post_content' => wp_kses_post( $lesson['content'] ?? '' ), 'post_status' => in_array( $lesson['status'] ?? 'draft', array( 'publish', 'draft' ), true ) ? $lesson['status'] : 'draft', 'post_type' => 'lesson' ); if ( $lesson_id ) { $existing = get_post( $lesson_id ); if ( ! $existing || ! in_array( $existing->post_type, array( 'lesson', 'ggm_lesson' ), true ) || (int) get_post_meta( $lesson_id, 'course', true ) !== (int) $course_id || ! current_user_can( 'edit_post', $lesson_id ) ) return new WP_Error( 'invalid_lesson', __( 'A lesson could not be edited for this course.', 'ggm-member-dashboard' ) ); $data['ID'] = $lesson_id; $data['post_type'] = $existing->post_type; $result = wp_update_post( wp_slash( $data ), true ); } else { if ( ! $data['post_title'] ) continue; $result = wp_insert_post( wp_slash( $data ), true ); $lesson_id = $result; } if ( is_wp_error( $result ) ) return $result; update_post_meta( $lesson_id, 'course', $course_id ); update_post_meta( $lesson_id, 'lesson_order', absint( $lesson['order'] ?? $order ) ); update_post_meta( $lesson_id, 'lesson_duration', sanitize_text_field( $lesson['duration'] ?? '' ) ); update_post_meta( $lesson_id, 'video_embed', ggm_sanitize_youtube_url( $lesson['video_embed'] ?? '' ) ); update_post_meta( $lesson_id, 'is_preview', ! empty( $lesson['is_preview'] ) ? '1' : '' ); foreach ( array( 'what_to_expect', 'best_practices', 'lesson_summary' ) as $key ) update_post_meta( $lesson_id, $key, sanitize_textarea_field( $lesson[ $key ] ?? '' ) ); update_post_meta( $lesson_id, 'lesson_resources_pdf', esc_url_raw( $lesson['lesson_resources_pdf'] ?? '' ) ); $focus = array(); foreach ( (array) ( $lesson['focus_areas'] ?? array() ) as $row ) if ( ! empty( $row['focus_area'] ) ) $focus[] = array( 'focus_area' => sanitize_text_field( $row['focus_area'] ) ); update_post_meta( $lesson_id, 'lesson_focus_areas', wp_json_encode( $focus ) ); }
		return true;
	}
}
